package stargate;

import classes.BlockElement;
import classes.Field;
import com.sun.org.apache.bcel.internal.util.Class2HTML;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.ItemEvent;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import javax.swing.border.LineBorder;
import sun.reflect.Reflection;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StargateShapeDesigner.java
 *
 * Created on 12.11.2011, 20:35:53
 */

/**
 *
 * @author Christopher
 */
public class StargateShapeDesigner extends javax.swing.JFrame {

    /** Creates new form StargateShapeDesigner */
    public StargateShapeDesigner() {
        initComponents();
        stargateSettings = new Settings();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        blocks = new stargate.unselectedButtonGroup();
        layers = new stargate.unselectedButtonGroup();
        EinstellungenTab = new javax.swing.JTabbedPane();
        OptionenPanel = new javax.swing.JPanel();
        stargate_name_label = new javax.swing.JLabel();
        GateName = new javax.swing.JTextField();
        woosh_ticks_label = new javax.swing.JLabel();
        light_ticks_label = new javax.swing.JLabel();
        woosh_ticks = new javax.swing.JComboBox();
        light_ticks = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        portal_material_label = new javax.swing.JLabel();
        portal_material = new javax.swing.JComboBox();
        iris_material_label = new javax.swing.JLabel();
        iris_material = new javax.swing.JComboBox();
        stargate_material_label = new javax.swing.JLabel();
        stargate_material = new javax.swing.JComboBox();
        light_material_label = new javax.swing.JLabel();
        active_material = new javax.swing.JComboBox();
        redstone_activated = new javax.swing.JCheckBox();
        jButton4 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        fieldWidth = new javax.swing.JTextField();
        fieldHeight = new javax.swing.JTextField();
        OKButton = new javax.swing.JButton();
        ZeichenPanel = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        fieldPanel = new stargate.FieldPanel();
        BlockPanel = new javax.swing.JPanel();
        stargateBlock = new javax.swing.JToggleButton();
        portalBlock = new javax.swing.JToggleButton();
        airBlock = new javax.swing.JToggleButton();
        redstoneGateActivatedBlock = new javax.swing.JToggleButton();
        redstoneActivateBlock = new javax.swing.JToggleButton();
        redstoneSignBlock = new javax.swing.JToggleButton();
        LayerPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Layer10 = new javax.swing.JToggleButton();
        Layer9 = new javax.swing.JToggleButton();
        Layer8 = new javax.swing.JToggleButton();
        Layer7 = new javax.swing.JToggleButton();
        Layer6 = new javax.swing.JToggleButton();
        Layer5 = new javax.swing.JToggleButton();
        Layer4 = new javax.swing.JToggleButton();
        Layer3 = new javax.swing.JToggleButton();
        Layer2 = new javax.swing.JToggleButton();
        Layer1 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        LayerText = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        EinstellungenTab.setName("Layer#1"); // NOI18N
        EinstellungenTab.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                include_textArea(evt);
            }
        });

        stargate_name_label.setText("Stargate Name");

        woosh_ticks_label.setText("\"Woosh\" - Ticks");

        light_ticks_label.setText("Light - Ticks");

        woosh_ticks.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", " " }));
        woosh_ticks.setSelectedIndex(3);

        light_ticks.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5" }));
        light_ticks.setSelectedIndex(2);

        portal_material_label.setText("Portal Material");

        portal_material.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Stilles Wasser", "Stille Lava", "Portal", "Luft" }));

        iris_material_label.setText("Iris Material");

        iris_material.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Stein", "Diamanten Block", "Glass", "Eisen Block", "Bedrock", "Obsidian", "Glowstone", "Lapis Lazuid Block" }));

        stargate_material_label.setText("Stargate Material");

        stargate_material.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Stein", "Diamanten Block", "Glass", "Eisen Block", "Bedrock", "Obsidian", "Glowstone", "Lapis Lazuid Block" }));
        stargate_material.setSelectedIndex(5);

        light_material_label.setText("Light Material");

        active_material.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Glowstone", "Glowing Redstone Ore" }));

        redstone_activated.setText("Redstone aktivierbar");

        jButton4.setText("Einstellungen speichern");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                einstellungen_speichern(evt);
            }
        });

        fieldWidth.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        fieldWidth.setText("" + Field.STANDARDCOLUMNS);

        fieldHeight.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        fieldHeight.setText("" + Field.STANDARDROWS);

        OKButton.setText("Setzen");
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Feld_setzen(evt);
            }
        });

        javax.swing.GroupLayout OptionenPanelLayout = new javax.swing.GroupLayout(OptionenPanel);
        OptionenPanel.setLayout(OptionenPanelLayout);
        OptionenPanelLayout.setHorizontalGroup(
            OptionenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OptionenPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OptionenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OptionenPanelLayout.createSequentialGroup()
                        .addComponent(redstone_activated)
                        .addContainerGap())
                    .addGroup(OptionenPanelLayout.createSequentialGroup()
                        .addComponent(light_material_label)
                        .addContainerGap(752, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OptionenPanelLayout.createSequentialGroup()
                        .addGroup(OptionenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, OptionenPanelLayout.createSequentialGroup()
                                .addComponent(iris_material_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, OptionenPanelLayout.createSequentialGroup()
                                .addComponent(stargate_name_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(GateName, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, OptionenPanelLayout.createSequentialGroup()
                                .addGroup(OptionenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(woosh_ticks_label)
                                    .addComponent(portal_material_label)
                                    .addComponent(stargate_material_label))
                                .addGap(18, 18, 18)
                                .addGroup(OptionenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(active_material, javax.swing.GroupLayout.Alignment.TRAILING, 0, 222, Short.MAX_VALUE)
                                    .addComponent(stargate_material, javax.swing.GroupLayout.Alignment.TRAILING, 0, 222, Short.MAX_VALUE)
                                    .addComponent(iris_material, javax.swing.GroupLayout.Alignment.TRAILING, 0, 222, Short.MAX_VALUE)
                                    .addComponent(portal_material, javax.swing.GroupLayout.Alignment.TRAILING, 0, 222, Short.MAX_VALUE)
                                    .addGroup(OptionenPanelLayout.createSequentialGroup()
                                        .addComponent(woosh_ticks, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                        .addComponent(light_ticks_label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(light_ticks, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(36, 36, 36)
                        .addComponent(fieldWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OKButton)
                        .addGap(284, 284, 284))
                    .addGroup(OptionenPanelLayout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addContainerGap(671, Short.MAX_VALUE))))
        );
        OptionenPanelLayout.setVerticalGroup(
            OptionenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OptionenPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OptionenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stargate_name_label)
                    .addComponent(GateName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OKButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OptionenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(woosh_ticks_label)
                    .addComponent(light_ticks_label)
                    .addComponent(light_ticks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(woosh_ticks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(OptionenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(portal_material_label)
                    .addComponent(portal_material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(OptionenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iris_material_label)
                    .addComponent(iris_material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(OptionenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stargate_material_label)
                    .addComponent(stargate_material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(OptionenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(light_material_label)
                    .addComponent(active_material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(redstone_activated)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(232, Short.MAX_VALUE))
        );

        EinstellungenTab.addTab("Einstellungen", OptionenPanel);

        ZeichenPanel.setPreferredSize(new java.awt.Dimension(820, 500));

        fieldPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                placeBlock(evt);
            }
        });

        javax.swing.GroupLayout fieldPanelLayout = new javax.swing.GroupLayout(fieldPanel);
        fieldPanel.setLayout(fieldPanelLayout);
        fieldPanelLayout.setHorizontalGroup(
            fieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 806, Short.MAX_VALUE)
        );
        fieldPanelLayout.setVerticalGroup(
            fieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 352, Short.MAX_VALUE)
        );

        blocks.add(stargateBlock);
        stargateBlock.setForeground(new java.awt.Color(255, 255, 255));
        stargateBlock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stargate/images/stargateBlock.jpg"))); // NOI18N
        stargateBlock.setBorder(null);
        stargateBlock.setMaximumSize(new java.awt.Dimension(40, 40));
        stargateBlock.setMinimumSize(new java.awt.Dimension(40, 40));
        stargateBlock.setName("StargateBlock"); // NOI18N
        stargateBlock.setPreferredSize(new java.awt.Dimension(40, 40));
        stargateBlock.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/stargate/images/stargateBlock_selected.jpg"))); // NOI18N
        stargateBlock.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/stargate/images/stargateBlock_selected.jpg"))); // NOI18N

        blocks.add(portalBlock);
        portalBlock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stargate/images/portalBlock.jpg"))); // NOI18N
        portalBlock.setBorder(null);
        portalBlock.setMaximumSize(new java.awt.Dimension(40, 40));
        portalBlock.setMinimumSize(new java.awt.Dimension(40, 40));
        portalBlock.setName("PortalBlock"); // NOI18N
        portalBlock.setPreferredSize(new java.awt.Dimension(40, 40));
        portalBlock.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/stargate/images/portalBlock_selected.jpg"))); // NOI18N
        portalBlock.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/stargate/images/portalBlock_selected.jpg"))); // NOI18N

        blocks.add(airBlock);
        airBlock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stargate/images/airBlock.jpg"))); // NOI18N
        airBlock.setBorder(null);
        airBlock.setMaximumSize(new java.awt.Dimension(40, 40));
        airBlock.setMinimumSize(new java.awt.Dimension(40, 40));
        airBlock.setName("AirBlock"); // NOI18N
        airBlock.setPreferredSize(new java.awt.Dimension(40, 40));
        airBlock.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/stargate/images/airBlock_selected.jpg"))); // NOI18N
        airBlock.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/stargate/images/airBlock_selected.jpg"))); // NOI18N

        blocks.add(redstoneGateActivatedBlock);
        redstoneGateActivatedBlock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stargate/images/redstoneGateActivatedBlock.jpg"))); // NOI18N
        redstoneGateActivatedBlock.setBorder(null);
        redstoneGateActivatedBlock.setMaximumSize(new java.awt.Dimension(40, 40));
        redstoneGateActivatedBlock.setMinimumSize(new java.awt.Dimension(40, 40));
        redstoneGateActivatedBlock.setPreferredSize(new java.awt.Dimension(40, 40));
        redstoneGateActivatedBlock.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/stargate/images/redstoneGateActivatedBlock_selected.jpg"))); // NOI18N
        redstoneGateActivatedBlock.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/stargate/images/redstoneGateActivatedBlock_selected.jpg"))); // NOI18N

        blocks.add(redstoneActivateBlock);
        redstoneActivateBlock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stargate/images/redstoneActivateBlock.jpg"))); // NOI18N
        redstoneActivateBlock.setBorder(null);
        redstoneActivateBlock.setMaximumSize(new java.awt.Dimension(40, 40));
        redstoneActivateBlock.setMinimumSize(new java.awt.Dimension(40, 40));
        redstoneActivateBlock.setPreferredSize(new java.awt.Dimension(40, 40));
        redstoneActivateBlock.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/stargate/images/redstoneActivateBlock_selected.jpg"))); // NOI18N
        redstoneActivateBlock.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/stargate/images/redstoneActivateBlock_selected.jpg"))); // NOI18N

        blocks.add(redstoneSignBlock);
        redstoneSignBlock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stargate/images/redstoneSignBlock.jpg"))); // NOI18N
        redstoneSignBlock.setBorder(null);
        redstoneSignBlock.setMaximumSize(new java.awt.Dimension(40, 40));
        redstoneSignBlock.setMinimumSize(new java.awt.Dimension(40, 40));
        redstoneSignBlock.setPreferredSize(new java.awt.Dimension(40, 40));
        redstoneSignBlock.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/stargate/images/redstoneSignBlock_selected.jpg"))); // NOI18N
        redstoneSignBlock.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/stargate/images/redstoneSignBlock_selected.jpg"))); // NOI18N

        javax.swing.GroupLayout BlockPanelLayout = new javax.swing.GroupLayout(BlockPanel);
        BlockPanel.setLayout(BlockPanelLayout);
        BlockPanelLayout.setHorizontalGroup(
            BlockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BlockPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BlockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BlockPanelLayout.createSequentialGroup()
                        .addComponent(redstoneSignBlock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(redstoneActivateBlock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(redstoneGateActivatedBlock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BlockPanelLayout.createSequentialGroup()
                        .addComponent(stargateBlock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(portalBlock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(airBlock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        BlockPanelLayout.setVerticalGroup(
            BlockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BlockPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BlockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(portalBlock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BlockPanelLayout.createSequentialGroup()
                        .addGroup(BlockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stargateBlock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(airBlock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BlockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(redstoneGateActivatedBlock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(redstoneActivateBlock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(redstoneSignBlock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel11.setText("Layer:");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("1");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("2");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("3");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("4");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("5");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("6");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("7");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("8");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("9");

        jLabel10.setText("10");

        layers.add(Layer10);
        Layer10.setName("Layer#10"); // NOI18N

        layers.add(Layer9);
        Layer9.setName("Layer#9"); // NOI18N

        layers.add(Layer8);
        Layer8.setName("Layer#8"); // NOI18N

        layers.add(Layer7);
        Layer7.setName("Layer#7"); // NOI18N

        layers.add(Layer6);
        Layer6.setName("Layer#6"); // NOI18N

        layers.add(Layer5);
        Layer5.setName("Layer#5"); // NOI18N

        layers.add(Layer4);
        Layer4.setName("Layer#4"); // NOI18N

        layers.add(Layer3);
        Layer3.setName("Layer#3"); // NOI18N

        layers.add(Layer2);
        Layer2.setName("Layer#2"); // NOI18N

        layers.add(Layer1);
        Layer1.setSelected(true);
        Layer1.setName("Layer#1"); // NOI18N

        javax.swing.GroupLayout LayerPanelLayout = new javax.swing.GroupLayout(LayerPanel);
        LayerPanel.setLayout(LayerPanelLayout);
        LayerPanelLayout.setHorizontalGroup(
            LayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayerPanelLayout.createSequentialGroup()
                .addGroup(LayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LayerPanelLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel11))
                    .addGroup(LayerPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel10))
                    .addGroup(LayerPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Layer1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(Layer2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(Layer3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(Layer4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(Layer5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(Layer6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(Layer7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(Layer8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(Layer9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(Layer10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LayerPanelLayout.setVerticalGroup(
            LayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayerPanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel11)
                .addGap(6, 6, 6)
                .addGroup(LayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(6, 6, 6)
                .addGroup(LayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Layer1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Layer2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Layer3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Layer4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Layer5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Layer6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Layer7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Layer8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Layer9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Layer10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jRadioButton1.setText("Schild mit Name");
        jRadioButton1.setName("N"); // NOI18N

        jRadioButton2.setText("Ziel Auswahlschild");
        jRadioButton2.setToolTipText("");
        jRadioButton2.setName("D"); // NOI18N

        jRadioButton3.setText("Iris Aktivierungs Schalter");
        jRadioButton3.setName("IA"); // NOI18N

        jRadioButton4.setText("Aktivierungs Schalter");
        jRadioButton4.setName("A"); // NOI18N

        jRadioButton5.setText("Teleport Spieler");
        jRadioButton5.setName("EP"); // NOI18N

        jRadioButton6.setText("Teleport Minecart");
        jRadioButton6.setName("EM"); // NOI18N

        jCheckBox1.setText("Light");
        jCheckBox1.setName("L"); // NOI18N

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextField1.setText("1");
        jTextField1.setName("lightnumber"); // NOI18N

        jButton1.setText("speichern");
        jButton1.setName("saveAttribute"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton4)
                            .addComponent(jRadioButton2))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCheckBox1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jRadioButton6)
                            .addComponent(jRadioButton5))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton6))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jCheckBox1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout ZeichenPanelLayout = new javax.swing.GroupLayout(ZeichenPanel);
        ZeichenPanel.setLayout(ZeichenPanelLayout);
        ZeichenPanelLayout.setHorizontalGroup(
            ZeichenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ZeichenPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ZeichenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ZeichenPanelLayout.createSequentialGroup()
                        .addComponent(BlockPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LayerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
                    .addComponent(fieldPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        ZeichenPanelLayout.setVerticalGroup(
            ZeichenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ZeichenPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ZeichenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ZeichenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(BlockPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LayerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        EinstellungenTab.addTab("Zeichnen", ZeichenPanel);

        TextArea.setColumns(20);
        TextArea.setEditable(false);
        TextArea.setRows(5);
        jScrollPane1.setViewportView(TextArea);

        javax.swing.GroupLayout LayerTextLayout = new javax.swing.GroupLayout(LayerText);
        LayerText.setLayout(LayerTextLayout);
        LayerTextLayout.setHorizontalGroup(
            LayerTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 826, Short.MAX_VALUE)
        );
        LayerTextLayout.setVerticalGroup(
            LayerTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
        );

        EinstellungenTab.addTab("Text", LayerText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EinstellungenTab, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EinstellungenTab, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Feld_setzen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Feld_setzen

        fieldPanel.initFieldElements(Integer.parseInt(fieldWidth.getText()),
                                      Integer.parseInt(fieldHeight.getText()));
    }//GEN-LAST:event_Feld_setzen


    private void einstellungen_speichern(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_einstellungen_speichern

        stargateSettings.setOptions(GateName.getText(),
                                   portal_material.getSelectedIndex(),
                                   iris_material.getSelectedIndex(),
                                   stargate_material.getSelectedIndex(),
                                   active_material.getSelectedIndex(),
                                   redstone_activated.isSelected(),
                                   woosh_ticks.getSelectedIndex(),
                                   light_ticks.getSelectedIndex());

    }//GEN-LAST:event_einstellungen_speichern


    private void include_textArea(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_include_textArea
        TextArea.setText(stargateSettings.toString());
    }//GEN-LAST:event_include_textArea

private void placeBlock(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_placeBlock
// TODO add your handling code here:
    Point p = evt.getPoint();
    int column = (int) (p.x / fieldPanel.getBlocksize());
    int row = (int) (p.y / fieldPanel.getBlocksize());
    
    String name = getSelectedButtonName();
    
    try {
        fieldPanel.setBlockElement((BlockElement) (Class.forName("classes." + name).newInstance()), column, row);
    } catch (ClassNotFoundException cnfE) {
        System.out.println("Kein Button ausgewählt");
        BlockElement blockelement = fieldPanel.getBlockElement(column, row);
        System.out.println(blockelement.toString());
    } catch (IllegalAccessException iaE) {
        
    } catch (InstantiationException iE) {
        
    }
}//GEN-LAST:event_placeBlock



    private String getSelectedButtonName() {
        
        String returnString = "";
        
        boolean isFound = false;
        
        Enumeration<AbstractButton> blockButtons = blocks.getElements();
        
        while(blockButtons.hasMoreElements() && !isFound) {
            JToggleButton button = (JToggleButton) blockButtons.nextElement();
            
            if(button.isSelected()) {
                returnString = button.getName();
                isFound = true;
            }
        }
        
        return returnString;
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StargateShapeDesigner().setVisible(true);
            }
        });
    }

    private Settings stargateSettings;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BlockPanel;
    private javax.swing.JTabbedPane EinstellungenTab;
    private javax.swing.JTextField GateName;
    private javax.swing.JToggleButton Layer1;
    private javax.swing.JToggleButton Layer10;
    private javax.swing.JToggleButton Layer2;
    private javax.swing.JToggleButton Layer3;
    private javax.swing.JToggleButton Layer4;
    private javax.swing.JToggleButton Layer5;
    private javax.swing.JToggleButton Layer6;
    private javax.swing.JToggleButton Layer7;
    private javax.swing.JToggleButton Layer8;
    private javax.swing.JToggleButton Layer9;
    private javax.swing.JPanel LayerPanel;
    private javax.swing.JPanel LayerText;
    private javax.swing.JButton OKButton;
    private javax.swing.JPanel OptionenPanel;
    private javax.swing.JTextArea TextArea;
    private javax.swing.JPanel ZeichenPanel;
    private javax.swing.JComboBox active_material;
    private javax.swing.JToggleButton airBlock;
    private stargate.unselectedButtonGroup blocks;
    private javax.swing.JTextField fieldHeight;
    private stargate.FieldPanel fieldPanel;
    private javax.swing.JTextField fieldWidth;
    private javax.swing.JComboBox iris_material;
    private javax.swing.JLabel iris_material_label;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField1;
    private stargate.unselectedButtonGroup layers;
    private javax.swing.JLabel light_material_label;
    private javax.swing.JComboBox light_ticks;
    private javax.swing.JLabel light_ticks_label;
    private javax.swing.JToggleButton portalBlock;
    private javax.swing.JComboBox portal_material;
    private javax.swing.JLabel portal_material_label;
    private javax.swing.JToggleButton redstoneActivateBlock;
    private javax.swing.JToggleButton redstoneGateActivatedBlock;
    private javax.swing.JToggleButton redstoneSignBlock;
    private javax.swing.JCheckBox redstone_activated;
    private javax.swing.JToggleButton stargateBlock;
    private javax.swing.JComboBox stargate_material;
    private javax.swing.JLabel stargate_material_label;
    private javax.swing.JLabel stargate_name_label;
    private javax.swing.JComboBox woosh_ticks;
    private javax.swing.JLabel woosh_ticks_label;
    // End of variables declaration//GEN-END:variables

}
